name: CI – Tests et coverage

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    backend-tests:
        name: Backend tests et coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup JDK 11
              uses: actions/setup-java@v4
              with:
                distribution: 'adopt'
                java-version: '11'

            - name: Build et run tests avec jacoco
              working-directory: back
              run: mvn clean verify

            - name: Upload le report de jacoco
              if: always() 
              uses: actions/upload-artifact@v4
              with:
                name: jacoco-report-backend
                path: back/target/site/jacoco
    frontend-tests:
        name : Frontend tests et coverage
        runs-on: ubuntu-latest
        steps :
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node latest
              uses: actions/setup-node@v4
              with: 
                node-version: 'lts/*'

            - name: Add dependencies
              working-directory: front
              run : npm ci

            - name: Tests angular
              working-directory: front
              run: npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless

            - name: Upload rapport coverage angular
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: angular-coverage-report
                path: front/coverage/bobapp

    sonarqube:
        name: Analyse qualité avec Sonarcloud
        runs-on: ubuntu-latest
        needs: [backend-tests, frontend-tests]
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Download jacoco report
              uses: actions/download-artifact@v4
              with:
                name: jacoco-report-backend
                path: back/target/site/jacoco

            - name: Download angular coverage report
              uses: actions/download-artifact@v4
              with:
                name: angular-coverage-report
                path: front/coverage/bobapp

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 'lts/*'

            - name: Install front dependencies
              working-directory: front
              run: npm ci

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: 'adopt'
                java-version: '11'
            
            - name: Compile backend
              working-directory: back
              run: mvn compile

            - name: Analyse Sonarcloud
              uses: SonarSource/sonarcloud-github-action@v2.0.2
              with:
                projectBaseDir: .
              env: 
                SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

    docker-deploy:
        name: Déploiement sur Docker Hub
        runs-on: ubuntu-latest
        needs: [backend-tests, frontend-tests, sonarqube]
        env: 
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        steps: 
          - name: Checkout
            uses: actions/checkout@v4

          - name: Connexion à Docker hub
            uses: docker/login-action@v3
            with: 
              username: ${{secrets.DOCKER_USERNAME}}
              password: ${{secrets.DOCKER_PASSWORD}}
          
          - name: Build & push back-end
            run: |
              docker build -t $DOCKER_USER/bobapp-backend ./back
              docker push $DOCKER_USER/bobapp-backend

          - name: Build & push front-end
            run: |
              docker build -t $DOCKER_USER/bobapp-frontend ./front
              docker push $DOCKER_USER/bobapp-frontend
        