name: CI – Tests et coverage

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    backend-tests:
        name: Backend tests et coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup JDK 11
              uses: actions/setup-java@v4
              with:
                distribution: 'adopt'
                java-version: '11'

            - name: Build et run tests avec jacoco
              working-directory: back
              run: mvn clean verify

            - name: Upload le report de jacoco
              #pour générer rapport même si ça plante
              if: always() 
              uses: actions/upload-artifact@v4
              with:
                name: jacoco-report-backend
                path: back/target/site/jacoco
    frontend-tests:
        name : Frontend tests et coverage
        runs-on: ubuntu-latest
        steps :
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node latest
              uses: actions/setup-node@v4
              with: 
                node-version: 'lts/*'

            - name: Add dependencies
              working-directory: front
              run : npm ci

            - name: Tests angular
              working-directory: front
              run: npm run test -- --code-coverage --watch=false --browsers=ChromeHeadless

            - name: Upload rapport coverage angular
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: angular-coverage-report
                path: front/coverage/bobapp

    sonarqube:
        name: Analyse qualité avec Sonarcloud
        runs-on: ubuntu-latest
        #On attend que les tests soient fini avant de lancer l'analyse
        needs: [backend-tests, frontend-tests]
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: 'adopt'
                java-version: '11'

            - name: Build backend
              working-directory: back
              run: mvn clean install -DskipTests

            - name: Analyse Sonarcloud
              uses: SonarSource/sonarcloud-github-action@v2.0.2
              with: 
                args: >
                    -Dsonar.organization=fhlabarbe
                    -Dsonar.projectKey=FHLabarbe_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
                    -Dsonar.java.binaries=back/target/classes
                    -Dsonar.sources=back/src/main/java,front/src
                    -Dsonar.exclusions=**/*.spec.ts
                    -Dsonar.tests=front/src
                    -Dsonar.test.inclusions=**/*.spec.ts
                    -Dsonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info
                    -Dsonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
              env: 
                SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}